site_name: Test MKDOCS
theme:
  features:
    - search
    - navigation.instant
  logo: /assets/arc.svg
  name: material
  font:
    text: Bebas Neue
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
